apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: goflow
  name: goflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goflow
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /goflow -kafka=false -logfmt=json 2>&1
        image: quay.io/rcarrillocruz/goflow
        imagePullPolicy: IfNotPresent
        name: goflow
      serviceAccountName: goflow
