apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: goflow
  name: goflow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: goflow
  name: goflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goflow
subjects:
- kind: ServiceAccount
  name: goflow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: goflow
  name: goflow
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
