apiVersion: v1
kind: Service
metadata:
  name: goflow
  namespace: default
  labels:
    app.kubernetes.io/name: goflow
spec:
  ports:
  - port: 2056
    protocol: UDP
  selector:
    app.kubernetes.io/name: goflow
